# Change these first
owner: Sulstice 
repo: Uptime-Regulatory 

sites:
  - name: Schedule I Drugs Wikipedia
    url: https://en.wikipedia.org/wiki/List_of_Schedule_I_drugs_(US)
  - name: Schedule 2 Drugs Wikipedia
    url: https://en.wikipedia.org/wiki/List_of_Schedule_II_drugs_(US)
  - name: Schedule 3 Drugs Wikipedia
    url: https://en.wikipedia.org/wiki/List_of_Schedule_III_drugs_(US)
  - name: Schedule 4 Drugs Wikipedia
    url: https://en.wikipedia.org/wiki/List_of_Schedule_IV_drugs_(US)
  - name: Schedule 5 Drugs Wikipedia
    url: https://en.wikipedia.org/wiki/List_of_Schedule_V_drugs_(US)
  - name: FDA Color Additive List
    url: https://www.fda.gov/industry/color-additive-inventories/color-additive-status-list
  - name: FDA Tainted Sexual Enhancements
    url: https://www.fda.gov/drugs/medication-health-fraud/tainted-sexual-enhancement-products
  - name: Cosmetics Colorant European Chemical Agency
    url: https://echa.europa.eu/cosmetics-colorant
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /Uptime-Regulatory
  name: Regulatory Chemical List Statuses
  introTitle: "Website Status of Regulatory Chemical Lists"
  introMessage: Welcome to the endpoint monitor of live regulatory chemical Lists. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
